baseURL = "https://socohist.netlify.com/"
languageCode = "en-us"
title = "SoCoHist"
theme = "beautifulhugo-theme"
disqusShortname = "socohist"
[blackfriday]
  hrefTargetBlank = true
enableRobotsTXT = true
