baseurl = "https://socohist.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "SoCoHist"
theme = "beautifulhugo-theme"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "socohist"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "SoCoHist" # Set a different text for the header on the home page
  subtitle = "Tim's tips & tricks to make research & writing fun & easy"
  mainSections = ["post","posts"]
  logo = "img/SoCo.png" # Expecting square dimensions
  favicon = "img/S.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Tim Blevins"
  website = "socohist.netlify.com"
  email = "youremail@domain.com"
  facebook = "username"
  github = "socohist"
  gitlab = "username"
  bitbucket = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"
  500px = "username"
  codepen = "username"
  mastodon = "url"
  kaggle = "username"
  weibo = "username"
  slack = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
